In [1]:
import torch
a=torch.tensor([4,9,2,6])
b=torch.tensor([[0,7,9,1],[4,9,2,6]])
print(a)
print(b)
print("This is attribute",b.shape)
print("This is size function",b.size())


tensor([4, 9, 2, 6])
tensor([[0, 7, 9, 1],
        [4, 9, 2, 6]])
This is attribute torch.Size([2, 4])
This is size function torch.Size([2, 4])


In [2]:
import torch
c=torch.tensor([1.2,33,45])
d=torch.full((3,5),7)
e=torch.empty(3)
k=torch.zeros(2,4)
l=torch.ones(2,4)
m=torch.arange(96,108,4)
n=torch.eye(5)
print(d)
print(c.dtype)
print(e)
print(k)
print(l)
print(m)
print(n)


tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])
torch.float32
tensor([2.2936e+38, 4.4678e-41, 2.2936e+38])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([ 96, 100, 104])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [3]:
import torch
t=torch.tensor([791,343,485,624])
l=torch.tensor([791,343,485,624,121,256])
'''print(t[1])
print(t[0:4])
print(t[:])
print(t[-1])'''
p=torch.tensor([[791,343,485,624],[1,3,5,7]])
k=torch.tensor([])
print(len(t))
print(t.numel())
print(t.device)
print(t.reshape(4,1))
print(t.reshape(2,2))
print(p.reshape(2,4))
print(p.reshape(2,-1))
print(t.reshape(2,-1))
print(l.reshape(3,-1))
#print(k.reshape(0,0))



4
4
cpu
tensor([[791],
        [343],
        [485],
        [624]])
tensor([[791, 343],
        [485, 624]])
tensor([[791, 343, 485, 624],
        [  1,   3,   5,   7]])
tensor([[791, 343, 485, 624],
        [  1,   3,   5,   7]])
tensor([[791, 343],
        [485, 624]])
tensor([[791, 343],
        [485, 624],
        [121, 256]])


In [4]:
import torch
a=torch.tensor(
    [
        [[1,2,3,4],
         [1,2,3,4]],
        [[1,2,3,4],
         [1,2,3,4]],
        [[1,2,3,4],
         [1,2,3,4]]
    ]
)
print(a.size())

torch.Size([3, 2, 4])
